title: Yet Another Mouse Review
description: A website dedicated to gaming mouse, mousepad, and audio reviews.
tagline: A website dedicated to gaming mouse, mousepad, and audio reviews.
url: "https://yetanothermousereview.com"       
baseurl: ""  # the subpath of your site, e.g. /blog
logo: /assets/img/site/logo.png

github_info:
   username: 'pnegus' 
   reponame: 'yetanothermousereview'

nav:
  - title: Home
    url: /
  - title: Mouse
    url: /mouse/
  - title: Mousepad
    url: /mousepad/
  - title: Audio
    url: /audio/
  - title: About
    url: /about/

# Build settings
postcss:
  cache: false

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
