title: Yet Another Mouse Review
description: >- # this means to ignore newlines until "baseurl:"
  A website that contains yet another mouse review

url: "https://yetanothermousereview.com"       
baseurl: ""  # the subpath of your site, e.g. /blog

github_info:
   username: 'pnegus' 
   reponame: 'yetanothermousereview'

header:
  - title: Home
    url: index
  - title: Mouse Reviews
    url: mouse_reviews
  - title: Mousepad Reviews
    url: mousepad_reviews
  - title: About
    url: about

paginate: 5
paginate_path: "/reviews/page:num/"

# Build settings
 
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-postcss
  - jekyll-paginate

plugins:
  - jekyll-postcss
  - jekyll-paginate

postcss:
  cache: false

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
