title: Yet Another Mouse Review
description: >- # this means to ignore newlines until "baseurl:"
  A website that contains yet another mouse review
tagline: A website dedicated to gaming mouse, mousepad, and audio reviews.
url: "https://yetanothermousereview.com"       
baseurl: ""  # the subpath of your site, e.g. /blog

logo: /assets/img/site/logo.png

github_info:
   username: 'pnegus' 
   reponame: 'yetanothermousereview'

nav:
  - title: Home
    url: /
  - title: Mouse Reviews
    url: /mouse/
  - title: Mousepad Reviews
    url: /mousepad/
  - title: Audio Reviews
    url: /audio/

# Build settings
postcss:
  cache: false

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
